"""empty message

Revision ID: 8af59486be97
Revises: 
Create Date: 2020-05-13 15:40:17.352789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8af59486be97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('article', 'creat_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('creat_time', mysql.DATETIME(), nullable=True))
    op.drop_column('article', 'create_time')
    # ### end Alembic commands ###
